version: '3'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1522:1522"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: devuser2
      APP_USER_PASSWORD: devpass